namespace StoreMMO.Models
{
	public class TemplateMail
	{
		public static string TemplateResetPass(string fullName, string link)
		{
		 string	body = "<!DOCTYPE html>\n"
			+ "\n"
			+ "<html lang=\"en\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:v=\"urn:schemas-microsoft-com:vml\">\n"
			+ "\n"
			+ "<head>\n"
			+ "	<title></title>\n"
			+ "	<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\" />\n"
			+ "	<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\" />\n"
			+ "	<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]-->\n"
			+ "	<style>\n"
			+ "		* {\n"
			+ "			box-sizing: border-box;\n"
			+ "		}\n"
			+ "\n"
			+ "		body {\n"
			+ "			margin: 0;\n"
			+ "			padding: 0;\n"
			+ "		}\n"
			+ "\n"
			+ "		a[x-apple-data-detectors] {\n"
			+ "			color: inherit !important;\n"
			+ "			text-decoration: inherit !important;\n"
			+ "		}\n"
			+ "\n"
			+ "		#MessageViewBody a {\n"
			+ "			color: inherit;\n"
			+ "			text-decoration: none;\n"
			+ "		}\n"
			+ "\n"
			+ "		p {\n"
			+ "			line-height: inherit\n"
			+ "		}\n"
			+ "\n"
			+ "		.desktop_hide,\n"
			+ "		.desktop_hide table {\n"
			+ "			mso-hide: all;\n"
			+ "			display: none;\n"
			+ "			max-height: 0px;\n"
			+ "			overflow: hidden;\n"
			+ "		}\n"
			+ "\n"
			+ "		.image_block img+div {\n"
			+ "			display: none;\n"
			+ "		}\n"
			+ "\n"
			+ "		@media (max-width:660px) {\n"
			+ "\n"
			+ "			.desktop_hide table.icons-inner,\n"
			+ "			.social_block.desktop_hide .social-table {\n"
			+ "				display: inline-block !important;\n"
			+ "			}\n"
			+ "\n"
			+ "			.icons-inner {\n"
			+ "				text-align: center;\n"
			+ "			}\n"
			+ "\n"
			+ "			.icons-inner td {\n"
			+ "				margin: 0 auto;\n"
			+ "			}\n"
			+ "\n"
			+ "			.image_block div.fullWidth {\n"
			+ "				max-width: 100% !important;\n"
			+ "			}\n"
			+ "\n"
			+ "			.mobile_hide {\n"
			+ "				display: none;\n"
			+ "			}\n"
			+ "\n"
			+ "			.row-content {\n"
			+ "				width: 100% !important;\n"
			+ "			}\n"
			+ "\n"
			+ "			.stack .column {\n"
			+ "				width: 100%;\n"
			+ "				display: block;\n"
			+ "			}\n"
			+ "\n"
			+ "			.mobile_hide {\n"
			+ "				min-height: 0;\n"
			+ "				max-height: 0;\n"
			+ "				max-width: 0;\n"
			+ "				overflow: hidden;\n"
			+ "				font-size: 0px;\n"
			+ "			}\n"
			+ "\n"
			+ "			.desktop_hide,\n"
			+ "			.desktop_hide table {\n"
			+ "				display: table !important;\n"
			+ "				max-height: none !important;\n"
			+ "			}\n"
			+ "		}\n"
			+ "	</style>\n"
			+ "</head>\n"
			+ "\n"
			+ "<body style=\"background-color: #f8f8f9; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;\">\n"
			+ "	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"nl-container\" role=\"presentation\"\n"
			+ "		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #f8f8f9;\" width=\"100%\">\n"
			+ "		<tbody>\n"
			+ "			<tr>\n"
			+ "				<td>\n"
			+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-1\"\n"
			+ "						role=\"presentation\"\n"
			+ "						style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #1aa19c;\" width=\"100%\">\n"
			+ "						<tbody>\n"
			+ "							<tr>\n"
			+ "								<td>\n"
			+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "										class=\"row-content stack\" role=\"presentation\"\n"
			+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; background-color: #1aa19c; width: 640px; margin: 0 auto;\"\n"
			+ "										width=\"640\">\n"
			+ "										<tbody>\n"
			+ "											<tr>\n"
			+ "												<td class=\"column column-1\"\n"
			+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\n"
			+ "													width=\"100%\">\n"
			+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "														class=\"divider_block block-1\" role=\"presentation\"\n"
			+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\n"
			+ "														width=\"100%\">\n"
			+ "														<tr>\n"
			+ "															<td class=\"pad\">\n"
			+ "																<div align=\"center\" class=\"alignment\">\n"
			+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "																		role=\"presentation\"\n"
			+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\n"
			+ "																		width=\"100%\">\n"
			+ "																		<tr>\n"
			+ "																			<td class=\"divider_inner\"\n"
			+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 4px solid #1AA19C;\">\n"
			+ "																				<span> </span>\n"
			+ "																			</td>\n"
			+ "																		</tr>\n"
			+ "																	</table>\n"
			+ "																</div>\n"
			+ "															</td>\n"
			+ "														</tr>\n"
			+ "													</table>\n"
			+ "												</td>\n"
			+ "											</tr>\n"
			+ "										</tbody>\n"
			+ "									</table>\n"
			+ "								</td>\n"
			+ "							</tr>\n"
			+ "						</tbody>\n"
			+ "					</table>\n"
			+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-2\"\n"
			+ "						role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
			+ "						<tbody>\n"
			+ "							<tr>\n"
			+ "								<td>\n"
			+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "										class=\"row-content stack\" role=\"presentation\"\n"
			+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 640px; margin: 0 auto;\"\n"
			+ "										width=\"640\">\n"
			+ "										<tbody>\n"
			+ "											<tr>\n"
			+ "												<td class=\"column column-1\"\n"
			+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\n"
			+ "													width=\"100%\">\n"
			+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "														class=\"image_block block-1\" role=\"presentation\"\n"
			+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\n"
			+ "														width=\"100%\">\n"
			+ "														<tr>\n"
			+ "															<td class=\"pad\"\n"
			+ "																style=\"width:100%;padding-right:0px;padding-left:0px;\">\n"
			+ "																<div align=\"center\" class=\"alignment\"\n"
			+ "																	style=\"line-height:10px\">\n"
			+ "																	<div style=\"max-width: 160px;\"><a href=\"\"\n"
			+ "																			style=\"outline:none\" tabindex=\"-1\"\n"
			+ "																			target=\"_blank\"><img alt=\"Your logo.\"\n"
			+ "																				height=\"auto\"\n"
			+ "																				src=\"https://i.ibb.co/TqMS1x8/imresizer-1710165374749.png?utm_source=zalo&utm_medium=zalo&utm_campaign=zalo\"\n"
			+ "																				style=\"display: block; height: auto; border: 0; width: 100%;\"\n"
			+ "																				title=\"Your logo.\" width=\"160\" /></a>\n"
			+ "																	</div>\n"
			+ "																</div>\n"
			+ "															</td>\n"
			+ "														</tr>\n"
			+ "													</table>\n"
			+ "												</td>\n"
			+ "											</tr>\n"
			+ "										</tbody>\n"
			+ "									</table>\n"
			+ "								</td>\n"
			+ "							</tr>\n"
			+ "						</tbody>\n"
			+ "					</table>\n"
			+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-3\"\n"
			+ "						role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
			+ "						<tbody>\n"
			+ "							<tr>\n"
			+ "								<td>\n"
			+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "										class=\"row-content stack\" role=\"presentation\"\n"
			+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #fff; color: #000000; width: 640px; margin: 0 auto;\"\n"
			+ "										width=\"640\">\n"
			+ "										<tbody>\n"
			+ "											<tr>\n"
			+ "												<td class=\"column column-1\"\n"
			+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\n"
			+ "													width=\"100%\">\n"
			+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "														class=\"image_block block-1\" role=\"presentation\"\n"
			+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\n"
			+ "														width=\"100%\">\n"
			+ "														<tr>\n"
			+ "															<td class=\"pad\" style=\"width:100%;\">\n"
			+ "																<div align=\"center\" class=\"alignment\"\n"
			+ "																	style=\"line-height:10px\">\n"
			+ "																	<div style=\"max-width: 640px;\"><a\n"
			+ "																			href=\"www.example.com\" style=\"outline:none\"\n"
			+ "																			tabindex=\"-1\" target=\"_blank\"><img\n"
			+ "																				alt=\"Image of lock & key.\" height=\"auto\"\n"
			+ "																				src=\"https://i.imgur.com/K8otx6w.gif\"\n"
			+ "																				style=\"display: block; height: auto; border: 0; width: 100%;\"\n"
			+ "																				title=\"Image of lock & key.\"\n"
			+ "																				width=\"640\" /></a></div>\n"
			+ "																</div>\n"
			+ "															</td>\n"
			+ "														</tr>\n"
			+ "													</table>\n"
			+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "														class=\"divider_block block-2\" role=\"presentation\"\n"
			+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\n"
			+ "														width=\"100%\">\n"
			+ "														<tr>\n"
			+ "															<td class=\"pad\" style=\"padding-top:30px;\">\n"
			+ "																<div align=\"center\" class=\"alignment\">\n"
			+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "																		role=\"presentation\"\n"
			+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\n"
			+ "																		width=\"100%\">\n"
			+ "																		<tr>\n"
			+ "																			<td class=\"divider_inner\"\n"
			+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 0px solid #BBBBBB;\">\n"
			+ "																				<span> </span>\n"
			+ "																			</td>\n"
			+ "																		</tr>\n"
			+ "																	</table>\n"
			+ "																</div>\n"
			+ "															</td>\n"
			+ "														</tr>\n"
			+ "													</table>\n"
			+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "														class=\"paragraph_block block-3\" role=\"presentation\"\n"
			+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\n"
			+ "														width=\"100%\">\n"
			+ "														<tr>\n"
			+ "															<td class=\"pad\"\n"
			+ "																style=\"padding-bottom:10px;padding-left:40px;padding-right:40px;padding-top:10px;\">\n"
			+ "																<div\n"
			+ "																	style=\"color:#555555;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:30px;line-height:120%;text-align:center;mso-line-height-alt:36px;\">\n"
			+ "																	<p style=\"margin: 0; word-break: break-word;\"><span\n"
			+ "																			style=\"color:#2b303a;\"><strong>Forgot Your\n"
			+ "																				Password?</strong></span></p>\n"
			+ "																</div>\n"
			+ "															</td>\n"
			+ "														</tr>\n"
			+ "													</table>\n"
			+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "														class=\"paragraph_block block-4\" role=\"presentation\"\n"
			+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\n"
			+ "														width=\"100%\">\n"
			+ "														<tr>\n"
			+ "															<td class=\"pad\"\n"
			+ "																style=\"padding-bottom:10px;padding-left:40px;padding-right:40px;padding-top:10px;\">\n"
			+ "																<div\n"
			+ "																	style=\"color:#555555;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:15px;line-height:150%;text-align:center;mso-line-height-alt:22.5px;\">\n"
			+ "																	<p style=\"margin: 0; word-break: break-word;\"><span\n"
			+ "																			style=\"color:#808389;text-align: left;float: left;\">Hi.\n"
			+ "																			<strong>" + fullName + "</strong> ,</span>\n"
			+ "																	</p> <br>\n"
			+ "																	<br>\n"
			+ "																	<p style=\"margin: 0; word-break: break-word;\"><span\n"
			+ "																			style=\"color:#808389;\">Congratulations on\n"
			+ "																			sending a successful password recovery\n"
			+ "																			request, please click on the button below to\n"
			+ "																			change the\n"
			+ "																			password.</span></p>\n"
			+ "																</div>\n"
			+ "															</td>\n"
			+ "														</tr>\n"
			+ "													</table>\n"
			+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "														class=\"button_block block-5\" role=\"presentation\"\n"
			+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\n"
			+ "														width=\"100%\">\n"
			+ "														<tr>\n"
			+ "															<td class=\"pad\"\n"
			+ "																style=\"padding-left:10px;padding-right:10px;padding-top:15px;text-align:center;\">\n"
			+ "																<div align=\"center\" class=\"alignment\"><!--[if mso]>\n"
			+ "<v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"www.example.com\" style=\"height:62px;width:209px;v-text-anchor:middle;\" arcsize=\"57%\" stroke=\"false\" fillcolor=\"#f7a50c\">\n"
			+ "<w:anchorlock/>\n"
			+ "<v:textbox inset=\"0px,0px,0px,0px\">\n"
			+ "<center dir=\"false\" style=\"color:#ffffff;font-family:Arial, sans-serif;font-size:16px\">\n"
			+ "<![endif]-->\n"
			+ "																	<a href=\"" + link + "\"\n"
			+ "																		style=\"background-color:#f7a50c;border-bottom:0px solid transparent;border-left:0px solid transparent;border-radius:35px;border-right:0px solid transparent;border-top:0px solid transparent;color:#ffffff;display:inline-block;font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:16px;font-weight:undefined;mso-border-alt:none;padding-bottom:15px;padding-top:15px;text-align:center;text-decoration:none;width:auto;word-break:keep-all;\"><span\n"
			+ "																			style=\"padding-left:30px;padding-right:30px;font-size:16px;display:inline-block;letter-spacing:normal;\"><span\n"
			+ "																				style=\"margin: 0; word-break: break-word; line-height: 32px;\"><strong>RESET\n"
			+ "																					PASSWORD</strong></span></span></a><!--[if mso]></center></v:textbox></v:roundrect><![endif]-->\n"
			+ "																</div>\n"
			+ "															</td>\n"
			+ "														</tr>\n"
			+ "													</table>\n"
			+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "														class=\"divider_block block-6\" role=\"presentation\"\n"
			+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\n"
			+ "														width=\"100%\">\n"
			+ "														<tr>\n"
			+ "															<td class=\"pad\"\n"
			+ "																style=\"padding-bottom:12px;padding-top:60px;\">\n"
			+ "																<div align=\"center\" class=\"alignment\">\n"
			+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "																		role=\"presentation\"\n"
			+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\n"
			+ "																		width=\"100%\">\n"
			+ "																		<tr>\n"
			+ "																			<td class=\"divider_inner\"\n"
			+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 0px solid #BBBBBB;\">\n"
			+ "																				<span> </span>\n"
			+ "																			</td>\n"
			+ "																		</tr>\n"
			+ "																	</table>\n"
			+ "																</div>\n"
			+ "															</td>\n"
			+ "														</tr>\n"
			+ "													</table>\n"
			+ "												</td>\n"
			+ "											</tr>\n"
			+ "										</tbody>\n"
			+ "									</table>\n"
			+ "								</td>\n"
			+ "							</tr>\n"
			+ "						</tbody>\n"
			+ "					</table>\n"
			+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-4\"\n"
			+ "						role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
			+ "						<tbody>\n"
			+ "							<tr>\n"
			+ "								<td>\n"
			+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "										class=\"row-content stack\" role=\"presentation\"\n"
			+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; background-color: #410125; width: 640px; margin: 0 auto;\"\n"
			+ "										width=\"640\">\n"
			+ "										<tbody>\n"
			+ "											<tr>\n"
			+ "												<td class=\"column column-1\"\n"
			+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\n"
			+ "													width=\"100%\">\n"
			+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "														class=\"image_block block-1\" role=\"presentation\"\n"
			+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\n"
			+ "														width=\"100%\">\n"
			+ "														<tr>\n"
			+ "															<td class=\"pad\"\n"
			+ "																style=\"width:100%;padding-right:0px;padding-left:0px;\">\n"
			+ "																<div align=\"center\" class=\"alignment\"\n"
			+ "																	style=\"line-height:10px\">\n"
			+ "																	<div class=\"fullWidth\" style=\"max-width: 416px;\"><a\n"
			+ "																			href=\"www.example.com\" style=\"outline:none\"\n"
			+ "																			tabindex=\"-1\" target=\"_blank\"><img\n"
			+ "																				alt=\"Your logo. \" height=\"auto\"\n"
			+ "																				src=\"https://i.imgur.com/ClCMU7k.png\"\n"
			+ "																				style=\"display: block; height: auto; border: 0; width: 100%;\"\n"
			+ "																				title=\"Your logo. \" width=\"416\" /></a>\n"
			+ "																	</div>\n"
			+ "																</div>\n"
			+ "															</td>\n"
			+ "														</tr>\n"
			+ "													</table>\n"
			+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "														class=\"social_block block-2\" role=\"presentation\"\n"
			+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\n"
			+ "														width=\"100%\">\n"
			+ "														<tr>\n"
			+ "															<td class=\"pad\"\n"
			+ "																style=\"padding-bottom:10px;padding-left:10px;padding-right:10px;padding-top:28px;text-align:center;\">\n"
			+ "																<div align=\"center\" class=\"alignment\">\n"
			+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "																		class=\"social-table\" role=\"presentation\"\n"
			+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block;\"\n"
			+ "																		width=\"208px\">\n"
			+ "																		<tr>\n"
			+ "																			<td style=\"padding:0 10px 0 10px;\"><a\n"
			+ "																					href=\"https://www.facebook.com\"\n"
			+ "																					target=\"_blank\"><img alt=\"Facebook\"\n"
			+ "																						height=\"auto\"\n"
			+ "																						src=\"https://i.imgur.com/CphiGv4.png\"\n"
			+ "																						style=\"display: block; height: auto; border: 0;\"\n"
			+ "																						title=\"Facebook\"\n"
			+ "																						width=\"32\" /></a></td>\n"
			+ "																			<td style=\"padding:0 10px 0 10px;\"><a\n"
			+ "																					href=\"https://www.twitter.com\"\n"
			+ "																					target=\"_blank\"><img alt=\"Twitter\"\n"
			+ "																						height=\"auto\"\n"
			+ "																						src=\"https://i.imgur.com/tL2iA8p.png\"\n"
			+ "																						style=\"display: block; height: auto; border: 0;\"\n"
			+ "																						title=\"Twitter\"\n"
			+ "																						width=\"32\" /></a></td>\n"
			+ "																			<td style=\"padding:0 10px 0 10px;\"><a\n"
			+ "																					href=\"https://www.instagram.com\"\n"
			+ "																					target=\"_blank\"><img alt=\"Instagram\"\n"
			+ "																						height=\"auto\"\n"
			+ "																						src=\"https://i.imgur.com/FEfpltU.png\"\n"
			+ "																						style=\"display: block; height: auto; border: 0;\"\n"
			+ "																						title=\"Instagram\"\n"
			+ "																						width=\"32\" /></a></td>\n"
			+ "																			<td style=\"padding:0 10px 0 10px;\"><a\n"
			+ "																					href=\"https://www.linkedin.com\"\n"
			+ "																					target=\"_blank\"><img alt=\"LinkedIn\"\n"
			+ "																						height=\"auto\"\n"
			+ "																						src=\"https://i.imgur.com/m797lAH.png\"\n"
			+ "																						style=\"display: block; height: auto; border: 0;\"\n"
			+ "																						title=\"LinkedIn\"\n"
			+ "																						width=\"32\" /></a></td>\n"
			+ "																		</tr>\n"
			+ "																	</table>\n"
			+ "																</div>\n"
			+ "															</td>\n"
			+ "														</tr>\n"
			+ "													</table>\n"
			+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "														class=\"divider_block block-3\" role=\"presentation\"\n"
			+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\n"
			+ "														width=\"100%\">\n"
			+ "														<tr>\n"
			+ "															<td class=\"pad\"\n"
			+ "																style=\"padding-bottom:10px;padding-left:40px;padding-right:40px;padding-top:25px;\">\n"
			+ "																<div align=\"center\" class=\"alignment\">\n"
			+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "																		role=\"presentation\"\n"
			+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\n"
			+ "																		width=\"100%\">\n"
			+ "																		<tr>\n"
			+ "																			<td class=\"divider_inner\"\n"
			+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 1px solid #555961;\">\n"
			+ "																				<span> </span>\n"
			+ "																			</td>\n"
			+ "																		</tr>\n"
			+ "																	</table>\n"
			+ "																</div>\n"
			+ "															</td>\n"
			+ "														</tr>\n"
			+ "													</table>\n"
			+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "														class=\"paragraph_block block-4\" role=\"presentation\"\n"
			+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\n"
			+ "														width=\"100%\">\n"
			+ "														<tr>\n"
			+ "															<td class=\"pad\"\n"
			+ "																style=\"padding-bottom:30px;padding-left:40px;padding-right:40px;padding-top:20px;\">\n"
			+ "																<div\n"
			+ "																	style=\"color:#555555;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:12px;line-height:120%;text-align:center;mso-line-height-alt:14.399999999999999px;\">\n"
			+ "																	<p style=\"margin: 0; word-break: break-word;\"><span\n"
			+ "																			style=\"color:#95979c;\">Your Logo Copyright ©\n"
			+ "																			2021</span></p>\n"
			+ "																	<p style=\"margin: 0; word-break: break-word;\"><span\n"
			+ "																			style=\"color:#95979c;\">Want to stop\n"
			+ "																			receiving these emails?</span></p>\n"
			+ "																	<p style=\"margin: 0; word-break: break-word;\"><span\n"
			+ "																			style=\"color:#95979c;\"> <a\n"
			+ "																				href=\"http://www.example.com\"\n"
			+ "																				rel=\"noopener\"\n"
			+ "																				style=\"text-decoration: underline; color: #ffffff;\"\n"
			+ "																				target=\"_blank\">Unsubscribe </a></span>\n"
			+ "																	</p>\n"
			+ "																</div>\n"
			+ "															</td>\n"
			+ "														</tr>\n"
			+ "													</table>\n"
			+ "												</td>\n"
			+ "											</tr>\n"
			+ "										</tbody>\n"
			+ "									</table>\n"
			+ "								</td>\n"
			+ "							</tr>\n"
			+ "						</tbody>\n"
			+ "					</table>\n"
			+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-5\"\n"
			+ "						role=\"presentation\"\n"
			+ "						style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;\" width=\"100%\">\n"
			+ "						<tbody>\n"
			+ "							<tr>\n"
			+ "								<td>\n"
			+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "										class=\"row-content stack\" role=\"presentation\"\n"
			+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; background-color: #ffffff; width: 640px; margin: 0 auto;\"\n"
			+ "										width=\"640\">\n"
			+ "										<tbody>\n"
			+ "											<tr>\n"
			+ "												<td class=\"column column-1\"\n"
			+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\n"
			+ "													width=\"100%\">\n"
			+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "														class=\"icons_block block-1\" role=\"presentation\"\n"
			+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: center;\"\n"
			+ "														width=\"100%\">\n"
			+ "														<tr>\n"
			+ "															<td class=\"pad\"\n"
			+ "																style=\"vertical-align: middle; color: #1e0e4b; font-family: 'Inter', sans-serif; font-size: 15px; padding-bottom: 5px; padding-top: 5px; text-align: center;\">\n"
			+ "																<table cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "																	role=\"presentation\"\n"
			+ "																	style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\n"
			+ "																	width=\"100%\">\n"
			+ "																	<tr>\n"
			+ "																		<td class=\"alignment\"\n"
			+ "																			style=\"vertical-align: middle; text-align: center;\">\n"
			+ "																			<!--[if vml]><table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;\"><![endif]-->\n"
			+ "																			<!--[if !vml]><!-->\n"
			+ "																			<table cellpadding=\"0\" cellspacing=\"0\"\n"
			+ "																				class=\"icons-inner\" role=\"presentation\"\n"
			+ "																				style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block; margin-right: -4px; padding-left: 0px; padding-right: 0px;\">\n"
			+ "																				<!--<![endif]-->\n"
			+ "																				<tr>\n"
			+ "																					<td\n"
			+ "																						style=\"vertical-align: middle; text-align: center; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 6px;\">\n"
			+ "																						<a href=\"http://designedwithbeefree.com/\"\n"
			+ "																							style=\"text-decoration: none;\"\n"
			+ "																							target=\"_blank\"><img\n"
			+ "																								align=\"center\"\n"
			+ "																								alt=\"Beefree Logo\"\n"
			+ "																								class=\"icon\"\n"
			+ "																								height=\"auto\"\n"
			+ "																								src=\"https://i.imgur.com/idGrkt4.png\"\n"
			+ "																								style=\"display: block; height: auto; margin: 0 auto; border: 0;\"\n"
			+ "																								width=\"34\" /></a>\n"
			+ "																					</td>\n"
			+ "																					<td\n"
			+ "																						style=\"font-family: 'Inter', sans-serif; font-size: 15px; font-weight: undefined; color: #1e0e4b; vertical-align: middle; letter-spacing: undefined; text-align: center;\">\n"
			+ "																						<a href=\"http://designedwithbeefree.com/\"\n"
			+ "																							style=\"color: #1e0e4b; text-decoration: none;\"\n"
			+ "																							target=\"_blank\">Designed\n"
			+ "																							with Beefree</a>\n"
			+ "																					</td>\n"
			+ "																				</tr>\n"
			+ "																			</table>\n"
			+ "																		</td>\n"
			+ "																	</tr>\n"
			+ "																</table>\n"
			+ "															</td>\n"
			+ "														</tr>\n"
			+ "													</table>\n"
			+ "												</td>\n"
			+ "											</tr>\n"
			+ "										</tbody>\n"
			+ "									</table>\n"
			+ "								</td>\n"
			+ "							</tr>\n"
			+ "						</tbody>\n"
			+ "					</table>\n"
			+ "				</td>\n"
			+ "			</tr>\n"
			+ "		</tbody>\n"
			+ "	</table><!-- End -->\n"
			+ "</body>\n"
			+ "\n"
			+ "</html>";
			return body;
		}
	}
}
